version: 2
updates:
  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/New_York
    open-pull-requests-limit: 5
    rebase-strategy: auto
    groups:
      production-patches-and-minors:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-patches-and-minors:
        dependency-type: development
        update-types:
          - minor
          - patch
