[package]
name = "lokr-api"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5.3"
axum = "0.8.1"
serde = "1.0.217"
serde_json = "1.0.135"
sqlx = "0.8.3"
tokio = { version = "1.43.0", features = ["full"] }
utoipa = { version = "5.3.1", features = ["axum_extras"] }
